# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e8160e7e61cf433af4f70502185288e"
name = "speed-test"
application_url = "https://pak-dawakhana-app.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [ "https://pak-dawakhana-app.vercel.app/api/auth" ]

[app_proxy]
url = "https://pak-dawakhana-app.vercel.app/api/create-order"
subpath = "cod"
prefix = "apps"

[product.metafields.app.image_1]
name = "Single Pack Image"
type = "file_reference"
description = "Optional override for the single pack image."

  [product.metafields.app.image_1.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.price_2]
name = "2 Packs Price"
type = "number_decimal"

  [product.metafields.app.price_2.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.price_compare_2]
name = "2 Packs Compare At Price"
type = "number_decimal"

  [product.metafields.app.price_compare_2.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.image_2]
name = "2 Packs Image"
type = "file_reference"

  [product.metafields.app.image_2.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.price_3]
name = "3 Packs Price"
type = "number_decimal"

  [product.metafields.app.price_3.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.price_compare_3]
name = "3 Packs Compare At Price"
type = "number_decimal"

  [product.metafields.app.price_compare_3.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.image_3]
name = "3 Packs Image"
type = "file_reference"

  [product.metafields.app.image_3.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.badge_text]
name = "Bundle Badge Text"
type = "single_line_text_field"

  [product.metafields.app.badge_text.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.info_badge_1]
name = "Info Badge 1"
type = "single_line_text_field"

  [product.metafields.app.info_badge_1.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[product.metafields.app.info_badge_2]
name = "Info Badge 2"
type = "single_line_text_field"

  [product.metafields.app.info_badge_2.access]
  admin = "merchant_read_write"
  storefront = "public_read"
